- name: electricity_15min
  hf_repo: autogluon/chronos_datasets
  offset: -5376
  prediction_length: 24
  num_rolls: 1
- name: monash_traffic
  hf_repo: autogluon/chronos_datasets
  offset: -24
  prediction_length: 24
  num_rolls: 1